### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [tov/memoize#10]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by tov** [comment]
I’m getting

```
cabal: unrecognized 'upload' option `--doc'
```

Are you sure that’s supposed to work?

**Comment by expipiplus1** [comment]
You might be running a version of cabal which is too old. You could try using this script https://github.com/ekmett/lens/blob/7e269b3e79ee54c0b34e4c62770fa1220068b769/scripts/hackage-docs.sh

**Comment by tov** [comment]
I was using the latest cabal. But in any case, the script worked—thanks!
